"""empty message

Revision ID: 303e064de840
Revises: b7e62be89964
Create Date: 2021-03-17 15:26:53.620472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303e064de840'
down_revision = 'b7e62be89964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('taken_lat', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('taken_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'taken_lon')
    op.drop_column('photos', 'taken_lat')
    # ### end Alembic commands ###
