"""empty message

Revision ID: 46d875667f0e
Revises: f407610aefd9
Create Date: 2021-04-09 10:02:43.623829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d875667f0e'
down_revision = 'f407610aefd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'collection_id')
    # ### end Alembic commands ###
