"""empty message

Revision ID: 6b6653fa6e7e
Revises: c823095a2e28
Create Date: 2021-04-07 10:25:23.686588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6653fa6e7e'
down_revision = 'c823095a2e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'title')
    # ### end Alembic commands ###
