"""empty message

Revision ID: b7e62be89964
Revises: d68bdf4edc9e
Create Date: 2021-03-17 14:26:24.271723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e62be89964'
down_revision = 'd68bdf4edc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'location_id')
    # ### end Alembic commands ###
