"""empty message

Revision ID: c823095a2e28
Revises: 303e064de840
Create Date: 2021-03-17 15:32:03.450102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c823095a2e28'
down_revision = '303e064de840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###
