"""empty message

Revision ID: f407610aefd9
Revises: 6b6653fa6e7e
Create Date: 2021-04-07 10:55:47.491997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f407610aefd9'
down_revision = '6b6653fa6e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('taken_str', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'taken_str')
    # ### end Alembic commands ###
